version: "2"
services:
  mosquitto:
    container_name: mqtt_broker
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./mosquitto/config/:/mosquitto/config/
      - ./mosquitto/data/:/mosquitto/config/data/
      - ./mosquitto/log/:/mosquitto/log/
    ports:
      - 1883:1883
      - 9001:9001
